language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"


env:
  - DJANGO=1.7.10
  - DJANGO=1.8.6
  - DJANGO=1.9rc1


install:
  - pip install -q Django==$DJANGO requests flake8
  - pip install -q python-coveralls coverage
  - python setup.py install


before_script:
  - make flake8


after_success:
  - make coveralls

script:
  - make coverage
